services:
  - type: web
    name: rails
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
     - key: RAILS_MASTER_KEY
       sync: false
